name: Build Action
description: 'Dotnet Server SDK Build action.'
inputs:
  project_file:
    description: 'Path to the project file.'
    required: true

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: Display dotnet version
      shell: bash
      run: dotnet --version

    - name: Build
      shell: bash
      run: dotnet build -p:Configuration=Release ${{ inputs.project_file }}
