name: CI
on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci
        with:
          project_file: packages/telemetry/src/LaunchDarkly.ServerSdk.Telemetry.csproj
          test_project_file: packages/telemetry/test/LaunchDarkly.ServerSdk.Telemetry.Tests.csproj
          token: ${{ secrets.GITHUB_TOKEN }}

# TODO: figure out docs for this package
#  build-docs:
#      runs-on: ubuntu-latest
#      permissions:
#          id-token: write
#          contents: read
#      steps:
#        - uses: actions/checkout@v4
#        - uses: ./.github/actions/build-docs
