name: LaunchDarkly.ServerSdk.Telemetry CI
on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci
        with:
          project_file: pkgs/telemetry/src/LaunchDarkly.ServerSdk.Telemetry.csproj
          test_project_file: pkgs/telemetry/test/LaunchDarkly.ServerSdk.Telemetry.Tests.csproj

      - uses: ./.github/actions/build-docs
        with:
          workspace_path: pkgs/telemetry
